#!/bin/bash
#My Lab 1.7

#This command show the total of the regular files in the Directory ~/Pictures
totalf=`find ~/Pictures/ -maxdepth 1 -type f | awk '/\//{print ++c, $0}' | tail -n 1 | awk '{print $1}'`
echo "The total of Files on ~/Pictures directory is of $totalf files."

#This command will show the how much space on disk these files are using
totals=`find ~/Pictures/ -maxdepth 1 -type f | xargs du -shc | tail -n1 | awk '{print $1}'`
echo "The total of disk usage of all these files is $totals"

#This commands will show the 3 biguest regular files on ~/Pictures/

sizes=($(find ~/Pictures/ -maxdepth 1 -type f | xargs du -sh | sort | head -n3 | awk '{print $1}'))
filenames=($(find ~/Pictures/ -maxdepth 1 -type f | xargs du -sh | sort | head -n3 | awk '{print $2}' | cut -d "/" -f5))

while [ -z "$sizes[@]" ]
do
	echo ${filenames[$]} "  " ${sizes[$]};
done
